//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCC.WebGestion.presupuestos.desaceptacion {
    
    
    public partial class DesAceptarPresupuesto {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// eR control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PROT.ControlesEspeciales.Editor eR;
        
        /// <summary>
        /// C3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.elementos.Cajaedicion C3;
        
        /// <summary>
        /// vp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.edicion.VerPresupuesto vp;
        
        /// <summary>
        /// ObAcep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PROT.ControlesEspeciales.Texto ObAcep;
        
        /// <summary>
        /// eoe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.bases.EnlaceObjetoExterno eoe;
        
        /// <summary>
        /// vc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.edicion.VerCliente vc;
        
        /// <summary>
        /// tr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.WebGestion.presupuestos.desaceptacion.Trabajos tr;
        
        /// <summary>
        /// fac control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.WebGestion.presupuestos.desaceptacion.Facturas fac;
        
        /// <summary>
        /// acp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.bases.BotonNormal acp;
        
        /// <summary>
        /// cer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.bases.BotonSimple cer;
    }
}
