//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCC.WebGestion.presupuestos {
    
    
    /// <summary>
    /// presupuestos_DocumentoModeloVersion class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class presupuestos_DocumentoModeloVersion {
        
        /// <summary>
        /// pp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.edicion.ProcesarProcesando pp;
        
        /// <summary>
        /// v control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.edicion.VerArchivo v;
        
        /// <summary>
        /// a2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LCC.ControlesLCCGestion.bases.Check a2;
        
        /// <summary>
        /// e control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PROT.ControlesEspeciales.Etiqueta e;
    }
}
